# Generated by Django 3.0.6 on 2020-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('negotiable', models.BooleanField(default=False)),
            ],
        ),
    ]
