# Generated by Django 3.0.6 on 2020-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
