# Generated by Django 3.0.6 on 2020-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0002_add_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='image',
            new_name='default_image',
        ),
        migrations.AddField(
            model_name='add',
            name='aproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add',
            name='category',
            field=models.CharField(choices=[('Mobile Phone', 'Mobile Phone'), ('Audio/MP3', 'Audio/MP3')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add',
            name='condition',
            field=models.CharField(choices=[('Used', 'used'), ('New', 'New')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add',
            name='image_1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add',
            name='image_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add',
            name='location',
            field=models.CharField(choices=[('kumasi', 'kumasi'), ('Accra', 'Accra'), ('Tamale', 'Tamale')], max_length=200, null=True),
        ),
    ]
