# Generated by Django 3.0.6 on 2020-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0005_auto_20200605_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='location',
        ),
        migrations.RemoveField(
            model_name='add',
            name='price',
        ),
        migrations.AlterField(
            model_name='add',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
