# Generated by Django 3.0.6 on 2020-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0007_add_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
