# Generated by Django 3.0.6 on 2020-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0008_add_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='default_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
