# Generated by Django 3.0.6 on 2020-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0009_add_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='aproval',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
