# Generated by Django 3.0.6 on 2020-06-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0011_auto_20200607_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='user',
        ),
    ]
